site_name: Documentação Sustainow
site_url: https://joao-pedro-p-holanda.github.io/sustainow/
repo_url: https://github.com/Joao-Pedro-P-Holanda/sustainow

nav:
    - Home: index.md
    - Documentação:
          - Requisitos de Software: software-requirements-specification.md
          - Arquitetura e Tecnologias: tech-stack.md
    - Alternativas: alternatives.md

theme:
    name: material
    language: pt
    palette:
        - scheme: default
          media: "(prefers-color-scheme: light)"
          toggle:
              icon: material/brightness-7

              name: Mudar para modo escuro

        - scheme: slate
          media: "(prefers-color-scheme: dark)"
          toggle:
              icon: material/brightness-3
              name: Mudar para modo claro

    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16

    features:
        - navigation.footer
        - navigation.expand

extra:
    version:
        provider: mike
    social:
        - type: github
          icon: fontawesome/brands/github
          link: https://github.com/Joao-Pedro-P-Holanda/Palette-Lens
    alternate:
        - name: pt - Português
          link: /

plugins:
    - search
    - panzoom:
          full_screen: true

markdown_extensions:
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - pymdownx.superfences
